Added: '-force-prune' to remove workers not on the heartbeat list
cycloidio/goworker pull request #8
Opened 2021-06-30 16:52 UTC by xescugc

This will remove workers thare could be stuck but it's not backwards compatible if enabled

2021-07-01 13:57 UTC, xlr-8 requested changes
For which previous version would it fail?
Couldn't we check that the "prune workers" don't represent 100% of the fleet?
And if so, not do it - to avoid breaking the ones using the old lib?

2021-07-01 13:57 UTC, xlr-8 commented on CHANGELOG.md
> +  ([PR #8](https://github.com/cycloidio/goworker/issues/8))
Right link?

2021-07-01 13:57 UTC, xlr-8 commented on flags.go
> +// real working workers.
How would that work for onpremise setup? Anything that should be of concern?

2021-07-01 15:08 UTC, xescugc commented on flags.go
> +// real working workers.
The main issue would be to use it in conjuntion with running workers, the idea would be to restart all workers with the new version if this flag want's to be used. Old ones are ones that do not have the `heartbeat` logic which since [0.15](https://github.com/cycloidio/goworker/blob/master/CHANGELOG.md#015-2021-06-08) is enabled

2021-07-01 15:11 UTC, xescugc commented
> For which previous version would it fail?
Couldn't we check that the "prune workers" don't represent 100% of the fleet?
And if so, not do it - to avoid breaking the ones using the old lib?

The option is disabled by default for this reason. It'll fail if the version used of resque does not support `heartbeat` as all workers then would be considered as dead if they are not registered on the `heartbeat` list.

This flag is also just for cleanup, it does not need to be enabled all time normally.

2021-07-19 14:12 UTC, xlr-8 reviewed
LGTM if my understanding is correct

2021-07-19 14:12 UTC, xlr-8 commented on flags.go
> +// real working workers.
So as long as the flag is added to updated workers we're good?

2021-07-19 15:34 UTC, xescugc commented on flags.go
> +// real working workers.
Yes if the workers are using this lib with v0.15=> it'll work fine, if not this will "kill" any old worker.

2021-07-28 09:29 UTC, xlr-8 commented
What are we waiting for?

2021-07-30 10:06 UTC, merged