goworker: Added 'MaxAgeRetries' option to the Goworker
cycloidio/goworker pull request #9
Opened 2021-07-01 11:11 UTC by xescugc

This option is useful to automatically remove retried failed jobs from the 'failed' queue that exceede that duration, this
check will be done every 1m.

Also changed the 'failed.FailedAt' and added 'failed.RetriedAt' and switched them to type string. The main reason is
that the Ruby lib is setting those values in an specific format and Ruby can read multiple formats into one, but GO
cannot and we need to actually use the same ones or the unmarshaler does not work so I decided to switch them to
'string' and add helpers to set/get the values that will directly convert them.

All the logic has more or less been ported from the Ruby version, on how to remove failed jobs and how the data
is stored, as the 'MaxAgeRetries' is something unique from this GO version

2021-07-01 14:50 UTC, xlr-8 requested changes

2021-07-01 14:50 UTC, xlr-8 commented on goworker.go
> +	ok, err := client.SetNX(fmt.Sprintf("%s%s", workerSettings.Namespace, keyForCleaningExpiredRetries), os.Getpid(), cleaningExpiredRetriesInterval/2).Result()
What exactly does this do? And why not log something on `!ok` result?

2021-07-01 14:50 UTC, xlr-8 commented on goworker.go
> +			client.LRem(fmt.Sprintf("%sfailed", workerSettings.Namespace), 1, hopefullyUniqueValueWeCanUseToDeleteJob)
The logic behind this is not obvious, why setting and then removing?

2021-07-01 14:50 UTC, xlr-8 commented on worker.go
> +func (w *worker) UnmarshalJSON(b []byte) error {
Comment / Test?

2021-07-01 14:50 UTC, xlr-8 commented on failure.go
> +func (f *failure) GetRetriedAtTime() (time.Time, error) {
Comment / Test?

2021-07-02 12:20 UTC, xescugc commented
Added comments to the missing/unclear parts.

I will not add tests yet (tested it manually) as the full lib is without any tests and I want to make an internal refactor to facilitate testing and add testing for everything.

2021-07-19 12:28 UTC, xlr-8 approved these changes

2021-07-19 13:09 UTC, merged